# -*- mode: ruby -*-
# vi: set ft=ruby :

# Setup a global variable to be consistent about xcopy arguments.
$xcopyArgs = '/s /q /exclude:c:\\chocoroot\\.xcopyignore /i /y /h'

$memory = ENV['VM_MEMORY'] ? ENV['VM_MEMORY'].to_i : 4096
$cpus = ENV['VM_CPU'] ? ENV['VM_CPU'].to_i : 2

Vagrant.configure("2") do |config|
  config.vm.box = "chocolatey/test-environment"
  # Set Hostname to prevent error messages. https://github.com/hashicorp/vagrant/issues/12644
  config.vm.hostname = 'chocolatey-tests'
  config.vm.boot_timeout = 600

  # windows
  config.vm.guest = :windows
  config.windows.halt_timeout = 60
  config.windows.set_work_network = true

  # winrm
  config.vm.communicator = 'winrm'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'
  # https://github.com/hashicorp/vagrant/issues/6430
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  config.vm.provider "virtualbox" do |vb|
    vb.gui = ENV['VM_GUI'] ? ENV['VM_GUI'].to_s.downcase == 'true' : true
    vb.memory = $memory
    vb.cpus = $cpus
    vb.linked_clone = true
    vb.customize ['modifyvm', :id, '--vram', '128']
  end
  config.vm.provider "hyperv" do |h|
    # Use Dynamic memory.
    h.maxmemory = $memory
    h.cpus = $cpus
    h.linked_clone = true
    h.enable_checkpoints = false
  end


  # Disable the default vagrant share as we don't need it.
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # Allow passing in the username/password through environment variables.
  if ENV['VM_SMB_USERNAME'].nil? || ENV['VM_SMB_PASSWORD'].nil?
    config.vm.synced_folder '../', '/chocoRoot'
  else
    config.vm.synced_folder '../', '/chocoRoot', type: "smb", smb_username: ENV['VM_SMB_USERNAME'], smb_password: ENV['VM_SMB_PASSWORD']
  end

  config.vm.provision "shell", name: "prep", inline: <<-PREP
    cscript c:/windows/system32/slmgr.vbs /rearm | Out-Null
    Set-ExecutionPolicy Bypass -Scope Process -Force
    iex (irm https://community.chocolatey.org/install.ps1)

    Write-Host "($(Get-Date -Format "dddd MM/dd/yyyy HH:mm:ss K")) We are going to install some prerequisites now. This could take some time"
    choco install git pester visualstudio2022community visualstudio2022-workload-manageddesktop netfx-4.8-devpack -y --no-progress
    Import-Module $env:ChocolateyInstall/helpers/chocolateyProfile.psm1
    Update-SessionEnvironment
  PREP

  config.vm.provision "shell", name: "clear-build", inline: <<-CLEARBUILD
    Write-Host "($(Get-Date -Format "dddd MM/dd/yyyy HH:mm:ss K")) Clearing the Chocolatey source directory"
    Remove-Item -Path C:/code/choco -Recurse -Force -ErrorAction SilentlyContinue
    xcopy c:\\chocoroot\\* c:\\code\\choco #{$xcopyArgs}
  CLEARBUILD

  config.vm.provision "shell", name: "build", inline: <<-BUILD
    xcopy c:\\chocoroot\\* c:\\code\\choco #{$xcopyArgs}
    Push-Location c:/code/choco
    Write-Host "($(Get-Date -Format "dddd MM/dd/yyyy HH:mm:ss K")) Files have been copied, beginning build process."
    $CakeOutput = ./build.bat --verbosity=diagnostic --target=CI --testExecutionType=none --shouldRunalyze=false --shouldRunNuGet=false 2>&1

    if ($LastExitCode -ne 0) {
        Set-Content c:/chocoRoot/tests/buildOutput.log -Value $CakeOutput
        Write-Host "The build has failed. Please see the buildOutput.log file for details"
        exit $LastExitCode
    }

    Write-Host "($(Get-Date -Format "dddd MM/dd/yyyy HH:mm:ss K")) Build complete."
  BUILD

  config.vm.provision "shell", name: "clear-packages", inline: <<-CLEARPACKAGES
    Write-Host "($(Get-Date -Format "dddd MM/dd/yyyy HH:mm:ss K")) Clearing the packages directory"
    Remove-Item "$env:TEMP/chocolateyTests/packages" -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item "$env:TEMP/chocolateyTests/all-packages" -Recurse -Force -ErrorAction SilentlyContinue
  CLEARPACKAGES

  config.vm.provision "shell", name: "test", inline: <<-TEST
    xcopy c:\\chocoroot\\* c:\\code\\choco #{$xcopyArgs}
    # Purge any tests files that have been removed.
    rm -re -fo c:\\code\\choco\\tests
    xcopy c:\\chocoroot\\tests\\* c:\\code\\choco\\tests #{$xcopyArgs}
    Write-Host "($(Get-Date -Format "dddd MM/dd/yyyy HH:mm:ss K")) Starting Test Execution"
    Push-Location c:/code/choco
    # $env:TEST_KITCHEN = 1
    $env:VM_RUNNING = 1
    # The Invoke-Tests file will build the packages if the directory does not exist.
    # This will allow to rerun tests without packaging each time.
    ./Invoke-Tests.ps1 -SkipPackaging
    Copy-Item $env:ALLUSERSPROFILE/chocolatey/logs/testInvocations.log c:/chocoRoot/tests
    Copy-Item ./tests/testResults.xml c:/chocoRoot/tests
  TEST
end
