# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2022"
  # Set Hostname to prevent error messages. https://github.com/hashicorp/vagrant/issues/12644
  config.vm.hostname = 'chocolatey-tests'
  config.vm.boot_timeout = 600

  # windows
  config.vm.guest = :windows
  config.windows.halt_timeout = 60
  config.windows.set_work_network = true

  # winrm
  config.vm.communicator = 'winrm'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'
  # https://github.com/hashicorp/vagrant/issues/6430
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  config.vm.network :forwarded_port, guest: 5985, host: 14985, id: 'winrm', auto_correct: true
  config.vm.network :forwarded_port, guest: 3389, host: 14389, id: 'rdp', auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = ENV['VM_GUI'] ? ENV['VM_GUI'].to_s.downcase == 'true' : true
    vb.memory = ENV['VM_MEMORY'] ? ENV['VM_MEMORY'].to_i : 4096
    vb.cpus = ENV['VM_CPU'] ? ENV['VM_CPU'].to_i : 2
    vb.linked_clone = true
    vb.customize ['modifyvm', :id, '--vram', '128']
  end
  config.vm.provider "hyperv" do |h|
    h.memory = 4096
    h.cpus = 2
    h.linked_clone = true
    h.enable_checkpoints = false
  end

  config.vm.synced_folder '../', '/chocoRoot'

  config.vm.provision "shell", name: "prep", path: './vagrantShell/prep.ps1'
  config.vm.provision "shell", name: "build", path: './vagrantShell/build.ps1'
  config.vm.provision "shell", name: "clear-packages", path: './vagrantShell/clearPackages.ps1'
  config.vm.provision "shell", name: "test", path: './vagrantShell/test.ps1'
end
